<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KitHerramientas</AssemblyName>
    <RootNamespace>KitHerramientas.Desktop</RootNamespace>
    <Version>0.9.0</Version>
  </PropertyGroup>
</Project>
